# Generated by Django 3.0.8 on 2020-10-02 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2020, 10, 2), null=True, verbose_name='Fecha de Atencion')),
                ('hora', models.TimeField(default=datetime.time(20, 46, 20, 220830), verbose_name='Hora')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo de consulta')),
                ('exploracion', models.TextField(verbose_name='Exploracion Fisica')),
                ('instrucciones', models.TextField(verbose_name='Instrucciones Medicas')),
                ('estado', models.BooleanField(default=True)),
                ('diagnostico', models.ManyToManyField(to='appcore.Diagnostico')),
                ('gabinete', models.ManyToManyField(to='appcore.EstudioGabinete')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.Paciente')),
                ('sintoma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appcore.Sintoma')),
            ],
            options={
                'verbose_name': 'Receta Medica',
                'verbose_name_plural': 'Recetas Medicas',
            },
        ),
        migrations.CreateModel(
            name='TomarSignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appatencion.Receta')),
                ('signovital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appcore.SignoVital')),
            ],
            options={
                'verbose_name': 'Tomar Signo Vital',
                'verbose_name_plural': 'Tomar Signos Vitales',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2020, 10, 2), null=True, verbose_name='Fecha de Historia')),
                ('hora', models.TimeField(default=datetime.time(20, 46, 20, 224740), verbose_name='Hora')),
                ('historiaNo', models.CharField(max_length=50, verbose_name='Numero de Historia')),
                ('notas', models.TextField(verbose_name='Notas Internas')),
                ('estado', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.Paciente')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.Dosis')),
                ('duracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.Duracion')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.Frecuencia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.Medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appatencion.Receta')),
            ],
            options={
                'verbose_name': 'DetalleReceta',
                'verbose_name_plural': 'DetalleRecetas',
            },
        ),
        migrations.CreateModel(
            name='DetalleHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Antecedentes')),
                ('GrupoAntecedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.GrupoAntecedente')),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcore.Antecedente')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appatencion.Historia')),
            ],
            options={
                'verbose_name': 'Detalle Historia Clinica',
                'verbose_name_plural': 'Detalle Historias Clinicas',
            },
        ),
    ]
